# use Python 3.11 image
FROM python:3.11-alpine

# install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 3001
COPY master_assistant.py .

# run the application
CMD ["python", "master_assistant.py"]