# Use Python 3.11 image
FROM python:3.11-alpine
# Install dependencies
#WORKDIR /code
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 3001
COPY master_assistant.py .
# Run the application
CMD ["python", "master_assistant.py"]